- action:
  - entity_id: switch.lamp
    service: switch.turn_on
  alias: bat den ngu
  id: '1517755183860'
  condition:
  - condition: state
    entity_id: switch.lamp
    state: 'off'
  - condition: time
    after: '22:00:00'
    before: 05:00:00
  trigger:
  - above: '0.1'
    below: '0.5'
    entity_id: sensor.broadlink_sensor_light
    platform: numeric_state
  - minutes: /30
    seconds: 0
    platform: time
- action:
  - entity_id: switch.lamp
    service: switch.turn_off
  - entity_id: switch.bathroom_light
    service: switch.turn_on
  alias: tat den ngu
  trigger:
  - at: 05:30:15
    platform: time
  id: e34dd42275b145149469e131d8dc2389
- action:
  - service: timer.start
    data:
      entity_id: timer.kiemtramanhinh
  alias: tat man hinh
  condition: []
  id: '1518153784468'
  trigger:
  - entity_id: switch.pc
    from: 'on'
    platform: state
    to: 'off'
- action:
  - service: switch.turn_off
    data:
      entity_id: switch.monitor
  alias: kiemtra_manhinh1
  condition:
  - condition: state
    entity_id: switch.pc
    state: 'off'
  - condition: state
    entity_id: switch.monitor
    state: 'on'
  id: '1518674296143'
  trigger:
  - event_data:
      entity_id: timer.kiemtramanhinh
    event_type: timer.finished
    platform: event
- action:
  - data:
      entity_id: switch.lamp
    service: switch.turn_on
  alias: kiem tra bat den lamp
  id: '1519216537402'
  trigger:
  - below: '1'
    entity_id: sensor.broadlink_sensor_light
    platform: numeric_state
  condition:
  - after: '17:00:00'
    before: 05:31:00
    condition: time
  - condition: state
    entity_id: device_tracker.fcdbb3bdd3a2
    state: not_home
- action:
  - data:
      entity_id: switch.lamp
    service: switch.turn_off
  alias: kiem tra tat den lamp
  condition: []
  id: '1519219763452'
  trigger:
  - above: '0'
    entity_id: sensor.broadlink_sensor_light
    platform: numeric_state
- alias: Nhiệt độ máy lạnh
  trigger:
    platform: state
    entity_id: input_select.nhietdo
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.mitsu
      temperature: '{{ states(''input_select.nhietdo'') }}'
  id: 75cf2164512747bdae033cbe4200c06e
- alias: TBNhiệt độ máy lạnh
  trigger:
    platform: state
    entity_id: input_select.nhietdo
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data_template:
      message: 'Nhiệt độ máy lạnh được điều chỉnh sang {{ states(''input_select.nhietdo'')
        }} độ . '
      language: vi
  id: ac270309bee9465ab8440f6be10eb234
- alias: Chế độ quạt
  trigger:
    platform: state
    entity_id: input_select.fan
  action:
  - service: climate.set_fan_mode
    data_template:
      entity_id: climate.mitsu
      fan_mode: "{% if is_state('input_select.fan', 'Thấp') %}\n  low\n{% elif is_state('input_select.fan',\
        \ 'Trung bình') %}\n  mid\n{% elif is_state('input_select.fan', 'Cao') %}\n\
        \  high\n{% elif is_state('input_select.fan', 'Tự động') %}\n  auto\n{% endif\
        \ %}"
  id: be65975475954e1a9b378a746c74d550
- alias: TBChế độ quạt
  trigger:
    platform: state
    entity_id: input_select.fan
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data_template:
      message: 'Chế độ quạt máy lạnh được điều chỉnh sang {{ states(''input_select.fan'')
        }} . '
      language: vi
  id: e4e1a7cc9d6b4b89824268758dd38675
- trigger:
  - entity_id: sensor.test
    from: '0'
    platform: state
    to: '1'
  alias: chup hinh
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.camera_an_ninh
      filename: /tmp/dlink.jpg
  id: d858112ba04a4b0f9a0671d8ff1a13d9
- id: '1527385431342'
  alias: xac nhan ra khoi nha tat thiet bi
  trigger:
  - entity_id: binary_sensor.combine
    from: 'on'
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: script.thongbaoandroid
    data_template:
      value1: Xác nhận đã ra ngoài. Nhà MT sẽ tắt các thiết bị điện không cần thiết
  - service: switch.turn_off
    data:
      entity_id: switch.main_light_1
  - service: switch.turn_off
    data:
      entity_id: switch.main_light_2
  - service: switch.turn_off
    data:
      entity_id: switch.bathroom_light
  - service: switch.turn_off
    data:
      entity_id: switch.dress_room_light
  - service: switch.turn_off
    data:
      entity_id: switch.balcony_light
  - service: switch.turn_off
    data:
      entity_id: switch.air_conditioner
- alias: xac nhan da ve mo may lanh
  trigger:
  - entity_id: binary_sensor.combine
    from: 'off'
    platform: state
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: state
    entity_id: switch.air_conditioner
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.air_conditioner
  id: 1e28edd88a61417bba8d82f7c5500f36
- alias: xac nhan da ve mo den
  trigger:
  - entity_id: binary_sensor.combine
    from: 'off'
    platform: state
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: numeric_state
    entity_id: sensor.broadlink_sensor_light
    below: '2'
  - condition: time
    after: '16:00:00'
    before: '21:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.main_light_1
  - service: switch.turn_on
    entity_id: switch.main_light_2
  id: 02689aad98db43ad9f0399d3ac974e1c
- alias: Tu dong tuoi cay
  trigger:
  - platform: template
    value_template: "{% if states('sensor.o_am_at')|float < states('input_number.doamthap')|float\
      \ %}\n  true\n{% endif %}"
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.tree_pump
  id: e6d0d855c5ff46eabbdc80b69ebf582b
- alias: Tu dong tat tuoi cay
  trigger:
  - platform: template
    value_template: "{% if states('sensor.o_am_at')|float > states('input_number.doamcao')|float\
      \ %}\n  true\n{% endif %}"
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.tree_pump
  id: ed312c53115d491789dc8912d450f67f
- alias: Thông báo qua IFTTT
  trigger:
  - entity_id: sensor.test
    platform: state
    to: '1'
  condition:
  - condition: state
    entity_id: device_tracker.fcdbb3bdd3a2
    state: not_home
  action:
  - service: script.thongbaoandroid
    data_template:
      value1: Có chuyển động trong phòng MT
  id: 27d14ee099874c7fb77de73ebb4e7519
- alias: Thông báo chuyển động trong phòng
  trigger:
  - entity_id: sensor.test
    platform: state
    to: '1'
  condition:
  - condition: state
    entity_id: device_tracker.fcdbb3bdd3a2
    state: not_home
  action:
  - service: notify.Thong_bao
    data:
      title: Thông báo từ nhà MT
      message: Có chuyển động trong phòng MT
      data:
        renotify: 0
        url: https://minhthanhhome.duckdns.org/api/camera_proxy/camera.camera_an_ninh?api_password=emilybro
        image: https://minhthanhhome.duckdns.org/api/camera_proxy/camera.hinh_anh_tu_he_thong_an_ninh?api_password=emilybro
        vibrate:
        - 300
        - 100
        - 400
        badge: Thông báo từ phòng MT
        timestamp: '%m%d%H%M%S'
        actions:
        - action: open_camera
          title: Mở camera
  id: 19ac8aee0d0d43b69cb0695a230d9a18
- id: '1528210480241'
  alias: Tự động mở đèn nhà tắm vào ban đêm
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001f48d85
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0001b15d8b
    state: 'on'
  - after: '17:30:00'
    before: 06:00:00
    condition: time
  - condition: state
    entity_id: switch.bathroom_light
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.bathroom_light
- id: '1528210971097'
  alias: Tự động tắt đèn nhà tắm vào ban đêm
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001b15d8b
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0001f48d85
    state: 'off'
  - after: '17:30:00'
    before: 06:00:00
    condition: time
  - condition: state
    entity_id: switch.bathroom_light
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id:
    - switch.bathroom_light
    - switch.dress_room_light
- id: '1528212152902'
  alias: Tự động bật đèn phòng thay đồ ban đêm
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001b15d8b
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0001f48d85
    state: 'off'
  - after: '17:30:00'
    before: 06:00:00
    condition: time
  - condition: state
    entity_id: switch.dress_room_light
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.dress_room_light
- id: '1528782664593'
  alias: Tự động cập nhật nhiệt độ máy lạnh
  trigger:
  - entity_id: switch.air_conditioner
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: 00:00:02
  - service: climate.set_temperature
    data_template:
      entity_id: climate.mitsu
      temperature: '{{states("input_select.nhietdo")}}'
  - service: climate.set_fan_mode
    data_template:
      entity_id: climate.mitsu
      fan_mode: "{% if is_state('input_select.fan', 'Thấp') %}\n  low\n{% elif is_state('input_select.fan',\
        \ 'Trung bình') %}\n  mid\n{% elif is_state('input_select.fan', 'Cao') %}\n\
        \  high\n{% elif is_state('input_select.fan', 'Tự động') %}\n  auto\n{% endif\
        \ %}"
- id: '1528931259639'
  alias: Chỉnh âm lượng
  trigger:
  - entity_id: input_number.amluong
    platform: state
  condition: []
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.audio_engine
      volume_level: '{{states("input_number.amluong")|float/100}}'
- trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.giomonhac.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  action:
  - service: switch.turn_on
    entity_id: switch.main_speaker
  - service: media_player.volume_set
    data:
      entity_id: media_player.audio_engine
      volume_level: 0.4
  - service: media_extractor.play_media
    entity_id: media_player.audio_engine
    data_template:
      media_content_id: '{{states(''input_text.khongloi'')}}'
      media_content_type: music
  id: 56518fd1a4e1404c90654cd6ff8c5e6e
- trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (((states.input_datetime.giodingu.attributes.timestamp)
      - 900) | int | timestamp_custom(''%H:%M'', False)) }}'
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data:
      message: Prepare for sleep time, my boss. I will change MT home to sleep mode
        in 15 minutes
      language: en
  id: b6ee783634174a14a2bcb27778590300
- trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.giodingu.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data:
      message: Please go to bed right now, my boss.  I will wake you up tomorrow.
        Have a good night.
      language: en
  - service: switch.turn_on
    entity_id: switch.main_speaker
  - service: media_player.volume_set
    data:
      entity_id: media_player.audio_engine
      volume_level: 0.4
  - service: media_extractor.play_media
    entity_id: media_player.audio_engine
    data_template:
      media_content_id: '{{states(''input_text.khongloi'')}}'
      media_content_type: music
  - service: script.turn_on
    entity_id: script.go_to_sleep
  id: fbb7cc292b6d4e3793aeadbadd90ba07
- id: '1529845679677'
  alias: Của mở bên trong
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001f3d222
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.echo_1
    state: '1'
  - condition: state
    entity_id: sensor.echo
    state: '0'
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data:
      message: Tạm biệt
      language: vi
- id: '1529845748295'
  alias: của mở bên ngoài
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001f3d222
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.echo
    state: '1'
  - condition: state
    entity_id: sensor.echo_1
    state: '0'
  action:
  - service: tts.google_say
    entity_id: media_player.bedroom_speaker
    data:
      message: Xin chào vào phòng
      language: vi
- id: '1530283394933'
  alias: Tự động tắt loa
  trigger:
  - entity_id: media_player.audio_engine
    platform: state
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.main_speaker